--#include constants
--#include globals
--#include config

--#include oo
--#include v2
--#include bbox
--#include hitbox

--#include helpers

--#include actors
--#include button
--#include bubbles
--#include room
--#include smoke
--#include player
--#include spring
--#include spawn
--#include spikes

-- fade bubbles
-- x gravity
-- x downward collision
-- x wall slide
-- x add wall slide smoke
-- x fall down faster
-- x wall jump
-- x variable jump time
-- x test controller input
-- x add ice
-- x springs
-- x wall sliding on ice
-- x player spawn points
-- x spikes
-- x respawn player after death
-- add water
-- add butterflies
-- add flies
-- add gore when dying
-- make spikes bloodier
-- add ease in for spawn point
-- add coroutine for spawn point
-- vanishing platforms
-- lookup / lookdown sprites
-- go through right and come back left (?)
-- add tweaking menu
-- add second player
-- parallax b ackground
-- add trailing smoke particles when springing up
-- add multiple players / spawn points
-- add death mechanics
-- add score
-- camera shake
-- fades

--#include main