--#include constants
--#include globals
--#include config

--#include oo
--#include v2
--#include bbox
--#include hitbox

--#include helpers
--#include tween
--#include coroutines
--#include queues
--#include gfx

--#include actors
--#include button
--#include bubbles
--#include room
--#include smoke
--#include particle
--#include player
--#include spring
--#include spawn
--#include spikes
--#include moving_platform
--#include teleporter

-- fade bubbles
-- x gravity
-- x downward collision
-- x wall slide
-- x add wall slide smoko
-- x fall down faster
-- x wall jump
-- x variable jump time
-- x test controller input
-- x add ice
-- x springs
-- x wall sliding on ice
-- x player spawn points
-- x spikes
-- x respawn player after death
-- x add ease in for spawn point
-- x add coroutine for spawn point
-- x slippage when changing directions
-- x flip smoke correctly when wall sliding
-- x particles with sprites
-- x add gore particles and gored up tiles
-- x add gore on vertical surfaces
-- x make gore slippery
-- x add gore when dying
-- moving platforms
-- laser beam
-- add water
-- add butterflies
-- add flies
-- vanishing platforms
-- lookup / lookdown sprites
-- go through right and come back left (?)
-- x add second player
-- add trailing smoke particles when springing up
-- x add multiple players / spawn points
-- x add death mechanics
-- x add score
-- camera shake
-- fades

-- powerups
-- bomb
-- superspeed
-- invincibility
-- superjump
-- gravity tweak

-- x multiple players
-- x random player spawns
-- x player collision
-- x player kill
-- x player colors

--#include main
